landscapeMemberClasses: 
   - name: Platinum Membership
     category: Platinum
   - name: Gold Membership
     category: Gold
   - name: Silver Membership
     category: Silver
   - name: Academic Membership
     category: Academic
   - name: Non-Profit Membership 
     category: Nonprofit
   - name: End-User Membership
     category: End User Supporter
slug: cncf 
memberSuffix: ' (member)'
landscapeMemberCategory: CNCF Members
